# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dotnet1:
    image: dotnet1
    build:
      context: .
      dockerfile: dotnet1/Dockerfile
    ports:
      - 5000:80
    extra_hosts: 
      - "db:192.168.1.25"  
